# -*- coding: utf-8 -*-
from . import c_aduanas
from . import c_claveprodservicios
from . import c_ClaveUnidad
from . import c_Codigo_P
from . import c_forma_de_pago
from . import c_impuestos
from . import c_NumPedimentoAduana
from . import c_paises
from . import c_patente_aduanal
from . import c_regimen_fiscal
from . import c_tasa_cuota
from . import c_tipo_factor
from . import c_tipo_relacion
from . import c_uso_cfdi
from . import c_tipo_comprobante
from . import c_configuracion
from . import c_metodo_pago
from . import c_bancos